@startuml
actor Patient
participant "UserController" as UC
participant "IPatientService" as PS
participant "PatientRepository" as PR

LEVEL1
Patient -> UC : UpdateProfile(dto)
UC -> PS : UpdateProfile(dto)
PS -> PR : UpdateAsync(patient)
PR --> PS : Confirmation
PS --> UC : Ok(responseMessage)
UC --> Patient : Profile Updated Successfully
@enduml
